import type { components } from './generated/api-schema'

type ApiSchema<Name extends keyof components['schemas']> = components['schemas'][Name]

export type TaskStatus = ApiSchema<'TaskStatus'>

export interface UploadedFile { id: string; original_name: string; size: number; status: 'ready' | 'failed'; sheet_count: number; detected_sheet_count: number; skipped_sheet_count: number; row_count: number; error?: string }
export interface DatasetRegion { sheet_name: string; region_index: number; source_range: string; header_start_row: number; header_end_row: number; data_start_row: number; data_end_row: number }
export interface DatasetInfo { id: string; table_name: string; display_name: string; row_count: number; columns: Array<{name: string; display_name: string; data_type: string; null_count: number; sample_values: unknown[]; semantic_type: 'id' | 'name' | 'date' | 'amount' | 'percentage' | 'category' | 'metric' | 'unknown'; role: 'dimension' | 'measure' | 'identifier' | 'unknown'; unit?: string; currency?: string; default_aggregation: 'sum' | 'average' | 'count' | 'none'; semantic_confidence: number}>; source_region?: DatasetRegion }
export interface DatasetRelationship { left_dataset_id: string; left_dataset: string; left_field: string; right_dataset_id: string; right_dataset: string; right_field: string; confidence: number; reason: string; status: 'candidate' | 'confirmed' | 'rejected' }
export interface DatasetPreview { dataset_id: string; display_name: string; columns: DatasetInfo['columns']; rows: Array<Record<string, unknown> & {__row_id: number}>; page: number; page_size: number; total: number; data_revision: number }
export interface DatasetColumnProfile { name: string; display_name: string; data_type: string; null_count: number; null_ratio: number; distinct_count: number; minimum?: unknown; maximum?: unknown; sample_values: unknown[] }
export interface DatasetProfile { dataset_id: string; row_count: number; duplicate_count: number; columns: DatasetColumnProfile[]; data_revision: number }
export interface DatasetCorrectionRequest { expected_data_revision: number; cell_updates: Array<{row_id: number; column: string; value: unknown}>; metadata_updates: Array<{column: string; display_name?: string; semantic_type?: DatasetInfo['columns'][number]['semantic_type']; role?: DatasetInfo['columns'][number]['role']; unit?: string; currency?: string; default_aggregation?: DatasetInfo['columns'][number]['default_aggregation']}>; deleted_row_ids: number[]; added_rows: Record<string, unknown>[]; change_summary: string }
export interface DatasetCorrectionResult { dataset: DatasetInfo; data_revision: number; dataset_asset_id: string; dataset_revision_id: string; revision_number: number }
export interface DatasetAsset { id: string; name: string; description: string; status: 'active' | 'archived'; owner_id: string; latest_revision: number; created_at: string; updated_at: string }
export interface DatasetRevision { id: string; dataset_id: string; revision_number: number; parent_revision_id?: string; source_type: 'upload' | 'correction' | 'migration'; status: 'published' | 'archived'; content_hash: string; change_summary: string; tables: DatasetInfo[]; created_at: string }
export interface DatasetAssetDetail extends DatasetAsset { revisions: DatasetRevision[]; permission: 'owner' | 'editor' | 'viewer' }
export interface KnowledgeDocumentInput { title: string; content: string; source_name?: string }
export interface KnowledgeDocument extends KnowledgeDocumentInput { id: string; revision_id: string; chunk_count: number; created_at: string }
export interface KnowledgeBaseRevision { id: string; knowledge_base_id: string; revision_number: number; parent_revision_id?: string; status: 'published' | 'archived'; embedding_model: string; embedding_dimensions: number; content_hash: string; change_summary: string; documents: KnowledgeDocument[]; created_at: string }
export interface KnowledgeBaseSummary { id: string; name: string; description: string; status: 'active' | 'archived'; owner_id: string; latest_revision: number; document_count: number; chunk_count: number; created_at: string; updated_at: string }
export interface KnowledgeBaseDetail extends KnowledgeBaseSummary { revisions: KnowledgeBaseRevision[]; permission: 'owner' | 'editor' | 'viewer' }
export interface TaskKnowledgeBinding { knowledge_base_id: string; knowledge_base_name: string; revision_id: string; revision_number: number; embedding_model: string; bound_at: string }
export interface KnowledgeMatch { chunk_id: string; knowledge_base_id: string; knowledge_base_name: string; revision_id: string; revision_number: number; document_id: string; document_title: string; content: string; score: number; rank: number }
export interface MessageRecord { id: string; role: 'user' | 'assistant' | 'system'; content: string; created_at: string; sequence: number }
export interface EvidencePointer { evidence_id: string; row_index: number; field: string; raw_value: string; unit?: string; source_type?: 'cell' | 'derived'; formula?: string; input_pointers?: EvidencePointer[] }
export interface Insight { id: string; type: 'ratio' | 'change' | 'comparison' | 'ranking' | 'contribution' | 'anomaly' | 'risk' | 'reconciliation'; title: string; conclusion: string; significance: string; action?: string; value?: string; unit?: string; severity: 'info' | 'warning' | 'error'; evidence_refs: string[]; evidence_pointers: EvidencePointer[]; formula?: string; input_labels: string[] }
export interface DeliveryCheck { code: string; label: string; passed: boolean; severity: 'info' | 'warning' | 'error'; message: string }
export interface DeliveryGate { status: 'completed' | 'completed_with_warnings' | 'needs_clarification' | 'needs_review' | 'failed' | 'cancelled'; checks: DeliveryCheck[]; new_information_count: number; unresolved_error_count: number }
export interface Metric { label: string; value: string; change?: string; direction: 'up' | 'down' | 'flat' | 'neutral'; evidence_refs: string[]; evidence_pointers: EvidencePointer[] }
export interface Finding { title: string; detail: string; severity: 'info' | 'warning' | 'error'; evidence_refs: string[]; evidence_pointers: EvidencePointer[] }
export interface ChartSpec { id: string; title: string; chart_type: 'line' | 'bar' | 'stacked_bar' | 'pie' | 'waterfall' | 'scatter' | 'table'; dataset_ref: string; category_field: string; series: Array<{name: string; field: string}>; unit?: string; orientation?: 'vertical' | 'horizontal'; sort_order?: 'source' | 'category_asc' | 'value_desc'; max_items?: number; x_field?: string; y_field?: string; label_field?: string }
export interface CalculationDetail { id: string; tool_name: string; title: string; status: 'success' | 'error'; row_count: number; evidence_refs: string[]; query?: string; warnings: string[] }
export interface AnalysisDraft { title: string; summary: string; summary_evidence_refs: string[]; summary_evidence_pointers: EvidencePointer[]; metrics: Metric[]; findings: Finding[]; charts: ChartSpec[]; assumptions: string[]; warnings: string[]; suggested_questions: string[]; calculation_details?: CalculationDetail[]; insights?: Insight[]; delivery?: DeliveryGate; verification_level: 'legacy' | 'evidence' | 'cell' }
export interface TaskSnapshot { id: string; title: string; status: TaskStatus; progress: number; status_message: string; files: UploadedFile[]; messages: MessageRecord[]; datasets: DatasetInfo[]; relationships: DatasetRelationship[]; knowledge_bases: TaskKnowledgeBinding[]; result?: AnalysisDraft; clarification_question?: string; error?: string; active_run_id?: string; pending_run_id?: string; queue_position?: number; data_revision: number; created_at: string; updated_at: string }
export interface TaskListItem { id: string; title: string; status: TaskStatus; status_message: string; file_names: string[]; created_at: string; updated_at: string }
export interface EvidenceRecord { id: string; title: string; source: string; columns: string[]; rows: Record<string, unknown>[]; data_revision: number; source_dataset_ids: string[]; query?: string; query_hash?: string; created_at: string }
type GeneratedRunArtifact = ApiSchema<'RunArtifact'>
export type RunArtifact = Omit<GeneratedRunArtifact, 'message_id' | 'payload' | 'evidence_refs'> & { message_id?: string; payload: Record<string, unknown>; evidence_refs: string[] }
export interface TaskEvent { schema_version: number; id: number; task_id: string; event_type: string; status: TaskStatus; progress: number; message: string; payload: Record<string, unknown>; created_at: string }
export interface ReportSummary { id: string; task_id: string; title: string; status: 'draft' | 'ready' | 'failed' | 'archived'; latest_version: number; created_at: string; updated_at: string }
export interface ReportVersion { id: string; report_id: string; version_number: number; run_id: string; status: 'generating' | 'ready' | 'failed'; content: {analysis: AnalysisDraft; provenance: {task_id: string; run_id: string; data_revision: number; source_revision_ids: string[]; knowledge_revision_ids?: string[]; published_at: string}}; source_revision_ids: string[]; content_hash: string; html_path?: string; created_at: string }
export interface ReportDetail extends ReportSummary { versions: ReportVersion[] }
export interface ReportJob { id: string; task_id: string; run_id: string; status: 'queued' | 'generating' | 'ready' | 'failed'; report_id?: string; report_version_id?: string; error?: string; attempt_count: number; claimed_at?: string; created_at: string; updated_at: string }
export interface UploadFailure { name: string; code: string; message: string }
export interface UploadBatchResponse { outcome: 'success' | 'partial' | 'failed'; accepted_files: string[]; rejected_files: UploadFailure[]; task: TaskSnapshot }
export interface TaskListResponse { items: TaskListItem[]; total: number; page: number; page_size: number }
export interface WorkflowRun { id: string; task_id: string; question: string; status: string; parent_run_id?: string; entry_node: string; result?: AnalysisDraft; is_active: boolean; data_revision: number; message_sequence: number; claimed_at?: string; heartbeat_at?: string; attempt_count: number; error?: string; started_at: string; finished_at?: string }
